- name: Install ansible prerequisites

  hosts: "{{ build_hosts | default('vagrant-ssh') }}"
  gather_facts: false

  pre_tasks:

  - name: test configuration
    debug:
      msg: RUNNING PLAYBOOK FOR '{{ vm_name }}' VERSION '{{ vm_version }}'
    tags: [init]
  - name: testing ansible environment
    debug:
      msg: Connecting to host '{{ inventory_hostname }}' as user '{{ ansible_user }}'
    tags: [init]
  - name: Make local dist folder
    local_action:
      module: file
      state: directory
      path: "{{ local_dist_folder }}/"
    when: release_notes_locally is defined and release_notes_locally
    tags: [init]

  roles:
  - role: marvel-nccr.ansible_prerequisites
    tags: [prerequisites]

  - role: install_rabbitmq 

- name: set up the VM
  hosts: "{{ build_hosts | default('vagrant-ssh') }}"

  roles:

  - name: add user {{ vm_user }} with key
    role: marvel-nccr.add_user
    tags: [add_user]
    vars:
      add_user_name: "{{ vm_user }}"
      add_user_password: "{{ vm_password }}"
      add_user_groups:
      - "{{ vm_user }}"
      - sudo
      add_user_passwordless_sudo: true

  - role: marvel-nccr.simulationbase
    tags: [simulationbase]
    vars:
      simulationbase_vm_user: "{{ vm_user }}"
      simulationbase_hostname: "{{ vm_hostname }}"
      simulationbase_codes_folder: "{{ vm_codes_folder }}"
      simulationbase_tmz: Europe/Zurich

  - role: marvel-nccr.ubuntu_desktop
    tags: [ubuntu_desktop]
    vars:
      ubuntu_desktop_browser: "{{ vm_browser }}"
      ubuntu_desktop_vm_user: "{{ vm_user }}"
    when: not vm_headless

  - role: marvel-nccr.quantum_mobile_customizations
    tags: [qm_customizations]
    vars:
      qm_customizations_browser: "{{ vm_browser }}"
      qm_customizations_vm_user: "{{ vm_user }}"
      qm_customizations_vm_password: "{{ vm_password }}"
      qm_customizations_vm_name: "{{ vm_name }}"
      qm_customizations_vm_version: "{{ vm_version }}"
      qm_customizations_vm_author: "{{ vm_author }}"
      qm_customizations_headless: "{{ vm_headless }}"
      qm_customizations_examples_folder: "{{ vm_examples_folder }}"
      qm_customizations_data_folder: "{{ vm_data_folder }}"
      qm_customizations_readme_file: "{{ vm_readme_file }}"
      qm_customizations_homepage: "https://quantum-mobile.readthedocs.io"
      qm_customizations_urls:
        Quantum ESPRESSO: http://www.quantum-espresso.org/
        Wannier90: http://www.wannier.org

  - role: marvel-nccr.editors
    tags: [editors]
    vars:
      editors_vm_user: "{{ vm_user }}"

  - role: marvel-nccr.quantum_espresso
    tags: [quantum_espresso]
    vars:
      quantum_espresso_data_folder: "{{ vm_data_folder }}"
      quantum_espresso_version: 6.7.0
      quantum_espresso_src_archive: "{{ quantum_espresso_git_tag }}.tar.gz" 
      quantum_espresso_url: "https://github.com/QEF/q-e/archive/refs/tags/{{ quantum_espresso_src_archive }}"
  post_tasks:


