- name: set up the VM
  hosts: default
  vars:
    - run_tests: True
    - copy_examples: True
    - clean: False
  pre_tasks:
    - name: import global variables
      tags: always
      include_vars:
        file: globalconfig.yml
        name: globalconfig
  roles: 
    - role: common
      tags: common
    - role: customizations
      tags: customizations
    - role: editors
      tags: editors
    - role: scheduler
      tags: scheduler
    - role: simulationtools
      tags: simulationtools  # Install also QE from Ubuntu
#    - role: quantum-espresso
#      tags: quantum-espresso
    - role: aiida
      tags: aiida

