aiida_version: "0.9.1"
aiida_extras:
  - atomic_tools
aiida_run_folder: "{{ ansible_env.HOME }}/.aiida_run"
aiida_localhost_name: localhost
postgres_pw: "ne9N_LDK-*JSS"
postgres_db: aiidadb
postgres_user: aiida
aiida_venv: "{{ ansible_env.HOME }}/.virtualenvs/aiida"
qe_topdir: "/usr" # since we are installing it with APT
qe_executables:
  - pw
  - cp
  - pp
  - ph
  - neb

# pseudos
aiida_pseudopotentials:
  - name: sssp-pbe-efficiency
    file: SSSP_efficiency_pseudos.tar.gz
    url: https://archive.materialscloud.org/file/2018.0001/v3
    folder: SSSP_efficiency_pseudos
    home_page: http://materialscloud.org/sssp/
    description: >-
     Standard Solid State Pseudopotentials (efficiency) 
     for the PBE functional
