- name: set up aiida computers
  include_tasks: computer-setup.yml
  vars:
    aiida_computer_name: "{{ aiida_localhost_name }}"

- include_role:
    name: release_notes
  vars:
    section: "AiiDA"
    option: "computers"
    value: >-
        localhost has already been set up and configured.
        List all available computers with 'verdi computer list -a'
