---
- include_tasks: aiida-core.yml
  tags: aiida,aiida-core

- include_tasks: computers-setup.yml

# codes need to come after computers
- include_tasks: aiida-quantumespresso.yml
  tags: aiida-quantumespresso
  when: qe_executables is defined

- include_tasks: aiida-pps.yml pp={{ item }}
  tags: aiida-pps
  with_items: "{{ aiida_pseudopotentials }}"

